package numero;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author lelp8
 */
public class CalculadoraNumeros extends javax.swing.JFrame {
    
    private double num1, num2;
    
    
    AAbstract sum = new Sumar();
    AAbstract res = new Restar();
    AAbstract mult = new Multiplicacion();
    AAbstract div = new Division();
    /**
     * Creates new form NewJFrame
     */
    public CalculadoraNumeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botSumar = new javax.swing.JButton();
        botRestar = new javax.swing.JButton();
        botMult = new javax.swing.JButton();
        botDiv = new javax.swing.JButton();
        botBorrar = new javax.swing.JButton();
        txtNum1 = new javax.swing.JTextField();
        txtNum2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("CALCULADORA OPERACIONES");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("NÚMERO 1");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("NÚMERO 2");

        botSumar.setBackground(new java.awt.Color(7, 71, 86));
        botSumar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botSumar.setForeground(new java.awt.Color(255, 255, 255));
        botSumar.setText("SUMAR");
        botSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botSumarActionPerformed(evt);
            }
        });

        botRestar.setBackground(new java.awt.Color(7, 71, 86));
        botRestar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botRestar.setForeground(new java.awt.Color(255, 255, 255));
        botRestar.setText("RESTAR");
        botRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botRestarActionPerformed(evt);
            }
        });

        botMult.setBackground(new java.awt.Color(7, 71, 86));
        botMult.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botMult.setForeground(new java.awt.Color(255, 255, 255));
        botMult.setText("MULTIPLICAR");
        botMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botMultActionPerformed(evt);
            }
        });

        botDiv.setBackground(new java.awt.Color(7, 71, 86));
        botDiv.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botDiv.setForeground(new java.awt.Color(255, 255, 255));
        botDiv.setText("DIVISIÓN");
        botDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botDivActionPerformed(evt);
            }
        });

        botBorrar.setBackground(new java.awt.Color(255, 153, 0));
        botBorrar.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        botBorrar.setForeground(new java.awt.Color(255, 255, 255));
        botBorrar.setText("BORRAR");
        botBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botBorrarActionPerformed(evt);
            }
        });

        txtNum1.setCaretColor(new java.awt.Color(7, 86, 95));
        txtNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum1ActionPerformed(evt);
            }
        });

        txtNum2.setCaretColor(new java.awt.Color(7, 86, 95));
        txtNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNum2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botSumar)
                                .addComponent(botRestar))
                            .addGap(36, 36, 36)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botDiv)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(botMult)
                                    .addGap(46, 46, 46)
                                    .addComponent(botBorrar))))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botSumar)
                    .addComponent(botMult)
                    .addComponent(botBorrar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botRestar)
                    .addComponent(botDiv))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botMultActionPerformed
        num1=Double.parseDouble(txtNum1.getText());
        num2=Double.parseDouble(txtNum2.getText());
        JOptionPane.showMessageDialog(null,mult.operaciones(num1, num2));
    }//GEN-LAST:event_botMultActionPerformed

    private void txtNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum1ActionPerformed
        num1=Double.parseDouble(txtNum1.getText());
    }//GEN-LAST:event_txtNum1ActionPerformed

    private void txtNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNum2ActionPerformed
        num2=Double.parseDouble(txtNum2.getText());
    }//GEN-LAST:event_txtNum2ActionPerformed

    private void botSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botSumarActionPerformed
        num1=Double.parseDouble(txtNum1.getText());
        num2=Double.parseDouble(txtNum2.getText());
        JOptionPane.showMessageDialog(null,sum.operaciones(num1, num2));
    }//GEN-LAST:event_botSumarActionPerformed

    private void botRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botRestarActionPerformed
      num1=Double.parseDouble(txtNum1.getText());
        num2=Double.parseDouble(txtNum2.getText());
        JOptionPane.showMessageDialog(null,res.operaciones(num1, num2));
    }//GEN-LAST:event_botRestarActionPerformed

    private void botBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botBorrarActionPerformed
        txtNum1.setText("");
        txtNum2.setText("");
    }//GEN-LAST:event_botBorrarActionPerformed

    private void botDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botDivActionPerformed
        num1=Double.parseDouble(txtNum1.getText());
        num2=Double.parseDouble(txtNum2.getText());
        JOptionPane.showMessageDialog(null,div.operaciones(num1, num2));
    }//GEN-LAST:event_botDivActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraNumeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraNumeros().setVisible(true);
            }
        });
    }   

    public CalculadoraNumeros(double num1, double num2, double result, JButton botBorrar, JButton botDiv, JButton botMult, JButton botRestar, JButton botSumar, JLabel jLabel1, JLabel jLabel2, JLabel jLabel3, JPanel jPanel1, JTextField txtNum1, JTextField txtNum2) {
        this.num1 = num1;
        this.num2 = num2;
        this.botBorrar = botBorrar;
        this.botDiv = botDiv;
        this.botMult = botMult;
        this.botRestar = botRestar;
        this.botSumar = botSumar;
        this.jLabel1 = jLabel1;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jPanel1 = jPanel1;
        this.txtNum1 = txtNum1;
        this.txtNum2 = txtNum2;
    }

    

    

    public JTextField getTxtNum1() {
        return txtNum1;
    }

    public JTextField getTxtNum2() {
        return txtNum2;
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botBorrar;
    private javax.swing.JButton botDiv;
    private javax.swing.JButton botMult;
    private javax.swing.JButton botRestar;
    private javax.swing.JButton botSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNum1;
    private javax.swing.JTextField txtNum2;
    // End of variables declaration//GEN-END:variables
}
